theme: jekyll-theme-minimal
inc:
  # Blog Information
  title:        "Jekyll Incorporated"
  subtitle:     "Modern Jekyll based blog for companies"
  cover_image:  blog-cover.jpg
  logo:         logo.png
  
  # Company information
  company:      Incorporated
  url:          http://sendtoinc.com/
  facebook:     sendtoinc
  twitter:      sendtoinc
  gplus:        '101183822199340201470'
  about_link:   https://sendtoinc.com/about/
  
  # Product Information
  product_link: http://incorporated.sendtoinc.com/
  tagline:      "Get a modern blog for your company"
  
